### ISSUE TITLE
Build x86 linux binaries of faf-uid

### ISSUE THREAD

**Issue by Wesmania** [FAForever/uid#11]
It would be nice to have releases of 32-bit linux binaries, so those not yet on AMD64 yet can play FAF on linux too.

**Comment by muellni** [comment]
With distros dropping 32 bit support, I doubt that we find a 32 bit Linux user. But I can upload one...

**Comment by muellni** [comment]
I promise I'll build and upload one, once someone needs a 32 bit executable.
