### ISSUE TITLE
int_to_bytes.py not found when using build_linux.sh

### ISSUE THREAD

**Issue by b2ag** [FAForever/uid#5]
Following code looks for int_to_bytes.py in "build", which seems wrong, because it's not in that directory.
`mkdir build`
`cd build`
`cmake \`
`-DJSONCPP_LIBRARIES=$THIS_SCRIPT_DIR/jsoncpp-build/src/lib_json/libjsoncpp.a \`
`-DJSONCPP_INCLUDE_DIRS=$THIS_SCRIPT_DIR/jsoncpp-1.7.2/include \`
`-DCRYPTOPP_LIBRARIES=$THIS_SCRIPT_DIR/cryptopp/libcryptopp.a \`
`-DCRYPTOPP_INCLUDE_DIRS=$THIS_SCRIPT_DIR \`
`-DCMAKE_BUILD_TYPE=MinSizeRel \`
`-DUID_PUBKEY_BYTES=`./int_to_bytes.py $n`\`
`..`

**Comment by muellni** [comment]
fixed with cbf205ffd61d7ba2c8cf05814c7628579c1d92fd. Thanks
