### ISSUE TITLE
UID doesn't work if machine_info can't be initialized

### ISSUE THREAD

**Issue by micheljung** [FAForever/uid#7]
![image](https://cloud.githubusercontent.com/assets/1864183/21080650/acdba3c2-bfb4-11e6-9942-cd024485ddcf.png)

Because of this, affected users can't log in

**Comment by muellni** [comment]
does the legacy `uid.dll` work on this machine?

**Comment by micheljung** [comment]
Yes, it produces "invalid" instead of crashing.

**Comment by muellni** [comment]
Could you please test this executable?
[uid.zip](https://github.com/FAForever/uid/files/648411/uid.zip)
It should return `"invalid"` on all attributes except `["machine"]["os"]["type"]`=`"Windows"`
But it will still print an error to stderr, hope thats ok.

**Comment by muellni** [comment]
One thing that's unclear to me: if legacy `uid.dll` returns `"invalid"` on all attributes, this would lead to the same hash for all affected users. They'd all get detected as smurfs, right?

**Comment by micheljung** [comment]
Exactly, that's the biggest problem we're facing. I remember that 170 or so users were/are affected

**Comment by muellni** [comment]
I can reproduce this error by stopping the `Windows Management Instrumentation` service on my machine.

**Comment by muellni** [comment]
see https://github.com/FAForever/client/issues/523
